profile: test
zuul: 
  routes: 
     route1: 
        path: /163
        url: http://www.163.com
     route2: 
        path: /bd
        url: http://www.baidu.com
     route3: 
        path: /app/**
        serviceId: CONFIG-SERVER

