test: test
profile: test
spring:
  application:
    name: gateway-service
  cloud:       
    gateway: 
      routes:
      - id: 163_route                    
        uri: http://www.163.com/
        predicates:
          - Path=/gsGateWay/163
      - id: baidu                    
        uri: http://www.baidu.com/
        predicates:
          - Path=/bd
